#!/system/bin/sh
# Argon Fan Control Installer for LineageOS
# This script installs the fan control script to /vendor/etc/init.d/03ssh

TARGET_FILE="/vendor/etc/init.d/03ssh"
TARGET_DIR="/vendor/etc/init.d"

echo "==========================================="
echo " Argon Fan Control Installer for LineageOS"
echo "==========================================="
echo ""

# Check if running as root
if [ "$(id -u)" -ne 0 ]; then
    echo "Error: This script must be run as root (su)"
    exit 1
fi

# Check if target directory exists
if [ ! -d "$TARGET_DIR" ]; then
    echo "Creating directory $TARGET_DIR..."
    mkdir -p "$TARGET_DIR"
fi

# Remount /vendor as read-write if needed
echo "Remounting /vendor as read-write..."
mount -o rw,remount /vendor 2>/dev/null

echo ""
echo "Fan Configuration"
echo "-----------------"
echo "The fan speed is controlled based on CPU temperature."
echo "Temperature values are in Celsius (will be converted internally)."
echo "Fan speed values are percentages (0-100)."
echo ""

# Default values
DEFAULT_TEMP1=55
DEFAULT_TEMP2=60
DEFAULT_TEMP3=65
DEFAULT_SPEED1=0
DEFAULT_SPEED2=25
DEFAULT_SPEED3=50
DEFAULT_SPEED4=100
DEFAULT_SLEEP=120

# Function to read user input with default
read_value() {
    prompt="$1"
    default="$2"
    printf "%s [%s]: " "$prompt" "$default"
    read value
    if [ -z "$value" ]; then
        echo "$default"
    else
        echo "$value"
    fi
}

# Get temperature thresholds
echo "Enter temperature thresholds (in Celsius):"
TEMP1=$(read_value "  Temperature 1 (fan turns on)" "$DEFAULT_TEMP1")
TEMP2=$(read_value "  Temperature 2 (medium speed)" "$DEFAULT_TEMP2")
TEMP3=$(read_value "  Temperature 3 (high speed)" "$DEFAULT_TEMP3")

echo ""
echo "Enter fan speeds (0-100%):"
SPEED1=$(read_value "  Speed when below ${TEMP1}C" "$DEFAULT_SPEED1")
SPEED2=$(read_value "  Speed between ${TEMP1}C and ${TEMP2}C" "$DEFAULT_SPEED2")
SPEED3=$(read_value "  Speed between ${TEMP2}C and ${TEMP3}C" "$DEFAULT_SPEED3")
SPEED4=$(read_value "  Speed above ${TEMP3}C" "$DEFAULT_SPEED4")

echo ""
SLEEPTIME=$(read_value "Check interval in seconds" "$DEFAULT_SLEEP")

# Convert temperatures to millidegrees
TEMP1_MILLI=$((TEMP1 * 1000))
TEMP2_MILLI=$((TEMP2 * 1000))
TEMP3_MILLI=$((TEMP3 * 1000))

# Convert speeds to hex
to_hex() {
    printf "0x%02x" "$1"
}

SPEED1_HEX=$(to_hex "$SPEED1")
SPEED2_HEX=$(to_hex "$SPEED2")
SPEED3_HEX=$(to_hex "$SPEED3")
SPEED4_HEX=$(to_hex "$SPEED4")

echo ""
echo "Configuration Summary:"
echo "  Below ${TEMP1}C: ${SPEED1}% (${SPEED1_HEX})"
echo "  ${TEMP1}C - ${TEMP2}C: ${SPEED2}% (${SPEED2_HEX})"
echo "  ${TEMP2}C - ${TEMP3}C: ${SPEED3}% (${SPEED3_HEX})"
echo "  Above ${TEMP3}C: ${SPEED4}% (${SPEED4_HEX})"
echo "  Check interval: ${SLEEPTIME} seconds"
echo ""

printf "Install with these settings? [Y/n]: "
read confirm
if [ "$confirm" = "n" ] || [ "$confirm" = "N" ]; then
    echo "Installation cancelled."
    exit 0
fi

# Create the fan control script
echo "Creating fan control script..."

cat > "$TARGET_FILE" << EOF
#!/system/bin/sh
# Argon Fan Control for LineageOS
# Auto-generated by install-lineageos.sh
#
# Temperature thresholds: ${TEMP1}C, ${TEMP2}C, ${TEMP3}C
# Fan speeds: ${SPEED1}%, ${SPEED2}%, ${SPEED3}%, ${SPEED4}%

sleeptime=${SLEEPTIME}

while true
do
    cputemp=\$(cat /sys/class/thermal/thermal_zone0/temp)

    if [ \$cputemp -lt ${TEMP1_MILLI} ]; then
        fanspeed="${SPEED1_HEX}"
    elif [ \$cputemp -ge ${TEMP1_MILLI} ] && [ \$cputemp -lt ${TEMP2_MILLI} ]; then
        fanspeed="${SPEED2_HEX}"
    elif [ \$cputemp -ge ${TEMP2_MILLI} ] && [ \$cputemp -lt ${TEMP3_MILLI} ]; then
        fanspeed="${SPEED3_HEX}"
    elif [ \$cputemp -ge ${TEMP3_MILLI} ]; then
        fanspeed="${SPEED4_HEX}"
    fi

    i2cset -y 1 0x1a \$fanspeed
    sleep \$sleeptime
done
EOF

# Make executable
chmod 755 "$TARGET_FILE"

# Remount /vendor as read-only
echo "Remounting /vendor as read-only..."
mount -o ro,remount /vendor 2>/dev/null

echo ""
echo "==========================================="
echo " Installation complete!"
echo "==========================================="
echo ""
echo "The fan control script has been installed to:"
echo "  $TARGET_FILE"
echo ""
echo "The script will start automatically on next boot."
echo "To start it now, run:"
echo "  sh $TARGET_FILE &"
echo ""
